cuda_compiler_version:                          # [linux64]
  - None                                        # [linux64]
docker_image:                                   # [linux64]
  - quay.io/condaforge/linux-anvil-cos7-x86_64  # [linux64]
cudnn:                                          # [linux64]
  - undefined                                   # [linux64]
cdt_name:                                       # [linux64]
  - cos7                                        # [linux64]
